// Re-export local engine types without depending on the external types package.
export type {
  Point,
  HandLandmark,
  HandConfig,
  CursorStyle,
  CursorOutput,
  PoseName,
  PoseProbabilities,
  PoseThresholds,
  PoseThresholdMap,
  PoseAction,
  PoseActionMap,
  PoseOutput,
  GestureOutput,
  HandOutput,
  AirpointEvent,
  AirpointEventType,
  AirpointMoveEvent,
  AirpointClickEvent,
  AirpointScrollEvent,
  AirpointPoseEvent,
  AirpointGestureEvent,
  HandednessInfo,
  Handedness,
  AdaptedHandResult,
  HandTrackerOptions,
  HandTrackerResult,
} from "../shared-types";
